# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/Users/48534/maciek/inf/master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/Users/48534/maciek/inf/master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Users/48534/maciek/inf/master/CMakeFiles /mnt/d/Users/48534/maciek/inf/master/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Users/48534/maciek/inf/master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named master

# Build rule for target.
master: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 master
.PHONY : master

# fast build rule for target.
master/fast:
	$(MAKE) -f CMakeFiles/master.dir/build.make CMakeFiles/master.dir/build
.PHONY : master/fast

NEAT/Connection.o: NEAT/Connection.cpp.o

.PHONY : NEAT/Connection.o

# target to build an object file
NEAT/Connection.cpp.o:
	$(MAKE) -f CMakeFiles/master.dir/build.make CMakeFiles/master.dir/NEAT/Connection.cpp.o
.PHONY : NEAT/Connection.cpp.o

NEAT/Connection.i: NEAT/Connection.cpp.i

.PHONY : NEAT/Connection.i

# target to preprocess a source file
NEAT/Connection.cpp.i:
	$(MAKE) -f CMakeFiles/master.dir/build.make CMakeFiles/master.dir/NEAT/Connection.cpp.i
.PHONY : NEAT/Connection.cpp.i

NEAT/Connection.s: NEAT/Connection.cpp.s

.PHONY : NEAT/Connection.s

# target to generate assembly for a file
NEAT/Connection.cpp.s:
	$(MAKE) -f CMakeFiles/master.dir/build.make CMakeFiles/master.dir/NEAT/Connection.cpp.s
.PHONY : NEAT/Connection.cpp.s

NEAT/Generation.o: NEAT/Generation.cpp.o

.PHONY : NEAT/Generation.o

# target to build an object file
NEAT/Generation.cpp.o:
	$(MAKE) -f CMakeFiles/master.dir/build.make CMakeFiles/master.dir/NEAT/Generation.cpp.o
.PHONY : NEAT/Generation.cpp.o

NEAT/Generation.i: NEAT/Generation.cpp.i

.PHONY : NEAT/Generation.i

# target to preprocess a source file
NEAT/Generation.cpp.i:
	$(MAKE) -f CMakeFiles/master.dir/build.make CMakeFiles/master.dir/NEAT/Generation.cpp.i
.PHONY : NEAT/Generation.cpp.i

NEAT/Generation.s: NEAT/Generation.cpp.s

.PHONY : NEAT/Generation.s

# target to generate assembly for a file
NEAT/Generation.cpp.s:
	$(MAKE) -f CMakeFiles/master.dir/build.make CMakeFiles/master.dir/NEAT/Generation.cpp.s
.PHONY : NEAT/Generation.cpp.s

NEAT/Network.o: NEAT/Network.cpp.o

.PHONY : NEAT/Network.o

# target to build an object file
NEAT/Network.cpp.o:
	$(MAKE) -f CMakeFiles/master.dir/build.make CMakeFiles/master.dir/NEAT/Network.cpp.o
.PHONY : NEAT/Network.cpp.o

NEAT/Network.i: NEAT/Network.cpp.i

.PHONY : NEAT/Network.i

# target to preprocess a source file
NEAT/Network.cpp.i:
	$(MAKE) -f CMakeFiles/master.dir/build.make CMakeFiles/master.dir/NEAT/Network.cpp.i
.PHONY : NEAT/Network.cpp.i

NEAT/Network.s: NEAT/Network.cpp.s

.PHONY : NEAT/Network.s

# target to generate assembly for a file
NEAT/Network.cpp.s:
	$(MAKE) -f CMakeFiles/master.dir/build.make CMakeFiles/master.dir/NEAT/Network.cpp.s
.PHONY : NEAT/Network.cpp.s

NEAT/Neuron.o: NEAT/Neuron.cpp.o

.PHONY : NEAT/Neuron.o

# target to build an object file
NEAT/Neuron.cpp.o:
	$(MAKE) -f CMakeFiles/master.dir/build.make CMakeFiles/master.dir/NEAT/Neuron.cpp.o
.PHONY : NEAT/Neuron.cpp.o

NEAT/Neuron.i: NEAT/Neuron.cpp.i

.PHONY : NEAT/Neuron.i

# target to preprocess a source file
NEAT/Neuron.cpp.i:
	$(MAKE) -f CMakeFiles/master.dir/build.make CMakeFiles/master.dir/NEAT/Neuron.cpp.i
.PHONY : NEAT/Neuron.cpp.i

NEAT/Neuron.s: NEAT/Neuron.cpp.s

.PHONY : NEAT/Neuron.s

# target to generate assembly for a file
NEAT/Neuron.cpp.s:
	$(MAKE) -f CMakeFiles/master.dir/build.make CMakeFiles/master.dir/NEAT/Neuron.cpp.s
.PHONY : NEAT/Neuron.cpp.s

games/tictactoe/TicTacToe.o: games/tictactoe/TicTacToe.cpp.o

.PHONY : games/tictactoe/TicTacToe.o

# target to build an object file
games/tictactoe/TicTacToe.cpp.o:
	$(MAKE) -f CMakeFiles/master.dir/build.make CMakeFiles/master.dir/games/tictactoe/TicTacToe.cpp.o
.PHONY : games/tictactoe/TicTacToe.cpp.o

games/tictactoe/TicTacToe.i: games/tictactoe/TicTacToe.cpp.i

.PHONY : games/tictactoe/TicTacToe.i

# target to preprocess a source file
games/tictactoe/TicTacToe.cpp.i:
	$(MAKE) -f CMakeFiles/master.dir/build.make CMakeFiles/master.dir/games/tictactoe/TicTacToe.cpp.i
.PHONY : games/tictactoe/TicTacToe.cpp.i

games/tictactoe/TicTacToe.s: games/tictactoe/TicTacToe.cpp.s

.PHONY : games/tictactoe/TicTacToe.s

# target to generate assembly for a file
games/tictactoe/TicTacToe.cpp.s:
	$(MAKE) -f CMakeFiles/master.dir/build.make CMakeFiles/master.dir/games/tictactoe/TicTacToe.cpp.s
.PHONY : games/tictactoe/TicTacToe.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/master.dir/build.make CMakeFiles/master.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/master.dir/build.make CMakeFiles/master.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/master.dir/build.make CMakeFiles/master.dir/main.cpp.s
.PHONY : main.cpp.s

utils/JsonHelper.o: utils/JsonHelper.cpp.o

.PHONY : utils/JsonHelper.o

# target to build an object file
utils/JsonHelper.cpp.o:
	$(MAKE) -f CMakeFiles/master.dir/build.make CMakeFiles/master.dir/utils/JsonHelper.cpp.o
.PHONY : utils/JsonHelper.cpp.o

utils/JsonHelper.i: utils/JsonHelper.cpp.i

.PHONY : utils/JsonHelper.i

# target to preprocess a source file
utils/JsonHelper.cpp.i:
	$(MAKE) -f CMakeFiles/master.dir/build.make CMakeFiles/master.dir/utils/JsonHelper.cpp.i
.PHONY : utils/JsonHelper.cpp.i

utils/JsonHelper.s: utils/JsonHelper.cpp.s

.PHONY : utils/JsonHelper.s

# target to generate assembly for a file
utils/JsonHelper.cpp.s:
	$(MAKE) -f CMakeFiles/master.dir/build.make CMakeFiles/master.dir/utils/JsonHelper.cpp.s
.PHONY : utils/JsonHelper.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... master"
	@echo "... NEAT/Connection.o"
	@echo "... NEAT/Connection.i"
	@echo "... NEAT/Connection.s"
	@echo "... NEAT/Generation.o"
	@echo "... NEAT/Generation.i"
	@echo "... NEAT/Generation.s"
	@echo "... NEAT/Network.o"
	@echo "... NEAT/Network.i"
	@echo "... NEAT/Network.s"
	@echo "... NEAT/Neuron.o"
	@echo "... NEAT/Neuron.i"
	@echo "... NEAT/Neuron.s"
	@echo "... games/tictactoe/TicTacToe.o"
	@echo "... games/tictactoe/TicTacToe.i"
	@echo "... games/tictactoe/TicTacToe.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... utils/JsonHelper.o"
	@echo "... utils/JsonHelper.i"
	@echo "... utils/JsonHelper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

