#ifndef MASTER_SHAREDDEFINITIONS_H
#define MASTER_SHAREDDEFINITIONS_H

#define CONN_MUTATION_FACTOR 0.02f
#define GAMES_PER_ITER 200

#define NETWORK_MUTATION_PERCENTAGE_CHANCE 80
#define CONNECTION_MUTATION_PERCENTAGE_CHANCE 5
#define NEURON_MUTATION_PERCENTAGE_CHANCE 5


#define NEURON_MUTATION_FACTOR 0.02f
#define NEURON_INITIAL_FACTOR 0.05f

// How many children we will have
#define POPULATION_COUNT 1000

#define GENERATION_COUNT 100000
#define TEST_BATTLES_COUNT 10000

#define TIC_TAC_TOE_ACTION_SIZE 9
#define TIC_TAC_TOE_STATE_SIZE 18

#define INPUT_LAYER_COUNT 18
#define HIDDEN_LAYER_COUNT 25
#define OUTPUT_LAYER_COUNT 9


#define WIN 1.0
#define DRAW 0.0
#define LOSE -1
#define INVALID_PENALTY -10

#endif //MASTER_SHAREDDEFINITIONS_H
