#ifndef MASTER_SHAREDDEFINITIONS_H
#define MASTER_SHAREDDEFINITIONS_H

#define CONN_MUTATION_FACTOR 0.02f
#define GAMES_PER_ITER 250
#define NETWORK_MUTATION_CHANCE 80
#define CONNECTION_MUTATION_RATE 0.02
#define NEURON_MUTATION_RATE 0.02

// How many children we will have
#define POPULATION_COUNT 2000

#define GENERATION_COUNT 1000
#define TEST_BATTLES_COUNT 10000
#endif //MASTER_SHAREDDEFINITIONS_H
