#ifndef MASTER_SHAREDDEFINITIONS_H
#define MASTER_SHAREDDEFINITIONS_H

#define CONN_MUTATION_FACTOR 0.05f
#define GAMES_PER_ITER 2000
#define NETWORK_MUTATION_CHANCE 80
#define CONNECTION_MUTATION_RATE 0.2
#define NEURON_MUTATION_RATE 0.2

// How many children we will have
#define POPULATION_COUNT 1000

#define GENERATION_COUNT 10
#define TEST_BATTLES_COUNT 10000

#define TIC_TAC_TOE_ACTION_SIZE 9
#define TIC_TAC_TOE_STATE_SIZE 18

#define HIDDEN_LAYER_COUNT 25

#define BEST_COPY_COUNT 5

#define WIN 1.0
#define DRAW 0.0
#define LOSE -1
#define INVALID_PENALTY -10


#define FILENAME_BASE "test"

#endif //MASTER_SHAREDDEFINITIONS_H
